for DETECTOR in SHITOMASI HARRIS AKAZE BRISK FAST ORB SIFT
do
	for DESCRIPTOR in BRISK BRIEF ORB FREAK AKAZE SIFT
	do
		echo Running $DETECTOR/$DESCRIPTOR...
		./3D_object_tracking $DETECTOR $DESCRIPTOR
	done
done
